name: Docker Image CI

on:
  push:

jobs:
  
  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag neofuuka
      
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      
    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/neofuuka
        VERSION=force-newest
        
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        
        docker tag neofuuka $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
